spring:

  profiles:
    active: development
  application:
    name: cms-service
  cloud:
    config:
      uri: http://localhost:8888/

  config:
    import: optional:configserver:http://localhost:8888/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8092
